// AUTO-GENERATED by scripts/generate-article-og.py — do not edit by hand.
// Slugs that have a rendered card at public/og/articles/<slug>.png.
export const ARTICLE_OG_CARD_SLUGS = new Set<string>([
  "best-apps-for-health",
  "best-apps-for-peptide-tracking",
  "best-apps-for-tracking-supplements",
  "best-apps-managing-prescriptions",
  "best-free-medication-reminder-apps",
  "best-medication-reminder-apps",
  "best-medication-reminder-apps-android",
  "best-medication-reminder-apps-iphone",
  "best-pill-reminder-apps-for-seniors",
  "medication-reminder-app",
  "missed-dose-what-to-do",
  "multiple-daily-dose-reminders",
  "pill-reminder-app",
  "set-up-medication-reminder-health-app",
]);

/** Fallback card for /articles pages without their own rendered image. */
export const ARTICLE_OG_FALLBACK = "/og/articles/default.png";

export const ARTICLE_OG_WIDTH = 1200;
export const ARTICLE_OG_HEIGHT = 630;

/** Site-relative card path for a slug, falling back to the brand card. */
export function articleOgPath(slug: string): string {
  return ARTICLE_OG_CARD_SLUGS.has(slug) ? `/og/articles/${slug}.png` : ARTICLE_OG_FALLBACK;
}
