/**
 * Reusable SEO template for blog posts.
 *
 * Every SEO field (title, description, canonical, og/twitter tags, JSON-LD)
 * is derived from the post content itself, so a new post only needs its
 * body — `title` and `description` are optional overrides.
 *
 * Used by src/routes/blog.$slug.tsx.
 */
import type { BlogPost } from "@/lib/blog-posts";
import { hreflangLinks, ogLocaleMeta } from "@/lib/hreflang";
import { BLOG_OG_CARD_SLUGS } from "@/lib/blog-og-manifest";
import { faqAnchorId } from "@/lib/faq-snippet";

export const BLOG_SITE = {
  base: "https://doseroutine.com",
  name: "DoseRoutine",
  logo: "https://doseroutine.com/icon-512.png",
} as const;

/** A post with the SEO fields optional — they get auto-filled from content. */
export type BlogSeoInput = Omit<BlogPost, "title" | "description"> &
  Partial<Pick<BlogPost, "title" | "description">>;

export function blogPostUrl(slug: string) {
  return `${BLOG_SITE.base}/blog/${slug}`;
}

/** Trim to a whole sentence/word under `max` chars (meta-description safe). */
export function clampMeta(text: string, max = 158) {
  const clean = text.replace(/\s+/g, " ").trim();
  if (clean.length <= max) return clean;
  const cut = clean.slice(0, max - 1);
  const stop = Math.max(cut.lastIndexOf(". "), cut.lastIndexOf("; "));
  if (stop > max * 0.5) return cut.slice(0, stop + 1).trim();
  return `${cut.slice(0, cut.lastIndexOf(" ")).trim()}…`;
}

export type BlogSeo = {
  title: string;
  description: string;
  canonical: string;
  keywords: string;
  path: string;
  /** Absolute URL of the post's unique 1200x630 social card. */
  image: string;
  imageAlt: string;
  /** MIME type of `image`, derived from its extension. */
  imageType: string;
};

/** Site-wide social card used when a post has neither a hero nor a card. */
export const BLOG_FALLBACK_IMAGE = `${BLOG_SITE.base}/og/doseroutine-home.jpg`;

function absolute(url: string) {
  if (/^https?:\/\//i.test(url)) return url;
  return `${BLOG_SITE.base}${url.startsWith("/") ? "" : "/"}${url}`;
}

function imageMimeType(url: string) {
  const ext = url.split("?")[0].split("#")[0].split(".").pop()?.toLowerCase();
  if (ext === "jpg" || ext === "jpeg") return "image/jpeg";
  if (ext === "webp") return "image/webp";
  if (ext === "avif") return "image/avif";
  return "image/png";
}

/**
 * Per-post social card generated by scripts/generate-blog-og.py into
 * public/og/blog/<slug>.png. Re-run that script after adding a post.
 */
export function blogPostImageUrl(slug: string, featuredImage?: string) {
  if (featuredImage?.trim()) return absolute(featuredImage.trim());
  if (BLOG_OG_CARD_SLUGS.has(slug)) return `${BLOG_SITE.base}/og/blog/${slug}.png`;
  return BLOG_FALLBACK_IMAGE;
}

/** Auto-fill the SEO fields from post content, honouring explicit overrides. */
export function deriveBlogSeo(post: BlogSeoInput): BlogSeo {
  const title = post.title?.trim()
    ? post.title.trim()
    : clampMeta(`${post.heading} | ${BLOG_SITE.name}`, 60);
  const image = blogPostImageUrl(post.slug, post.featuredImage);
  const description = post.description?.trim()
    ? clampMeta(post.description)
    : clampMeta(post.intro || post.keyPoints?.[0] || post.heading);
  return {
    title,
    description,
    canonical: blogPostUrl(post.slug),
    keywords: (post.tags ?? []).map((t) => t.label).join(", "),
    path: `/blog/${post.slug}`,
    image,
    imageAlt: post.featuredImageAlt?.trim() || `${post.heading} — ${BLOG_SITE.name}`,
    imageType: imageMimeType(image),
  };
}

/** Head config for a post that no longer exists. */
export function blogPostNotFoundHead() {
  return {
    meta: [
      { title: `Update not found | ${BLOG_SITE.name}` },
      { name: "robots", content: "noindex" },
    ],
  };
}

/** The full reusable head() payload for any blog post. */
export function blogPostHead(post: BlogSeoInput) {
  const seo = deriveBlogSeo(post);
  const { canonical, title, description } = seo;

  return {
    meta: [
      { title },
      { name: "description", content: description },
      { name: "robots", content: "index, follow, max-image-preview:large" },
      { name: "author", content: BLOG_SITE.name },
      ...(seo.keywords ? [{ name: "keywords", content: seo.keywords }] : []),
      { property: "og:title", content: title },
      { property: "og:description", content: description },
      { property: "og:type", content: "article" },
      { property: "og:url", content: canonical },
      { property: "og:site_name", content: BLOG_SITE.name },
      { property: "og:image", content: seo.image },
      { property: "og:image:secure_url", content: seo.image },
      { property: "og:image:type", content: seo.imageType },
      ...(seo.image.includes("/og/blog/")
        ? [
            { property: "og:image:width", content: "1200" },
            { property: "og:image:height", content: "630" },
          ]
        : []),
      { property: "og:image:alt", content: seo.imageAlt },
      { property: "article:published_time", content: post.published },
      { property: "article:modified_time", content: post.updated },
      ...(post.category ? [{ property: "article:section", content: post.category }] : []),
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:site", content: "@doseroutine" },
      { name: "twitter:title", content: title },
      { name: "twitter:description", content: description },
      { name: "twitter:image", content: seo.image },
      { name: "twitter:image:alt", content: seo.imageAlt },
      ...ogLocaleMeta("en"),
    ],
    links: [{ rel: "canonical", href: canonical }, ...hreflangLinks(seo.path)],
    scripts: [
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "BlogPosting",
          speakable: {
            "@type": "SpeakableSpecification",
            cssSelector: [".dr-speakable-intro", ".dr-speakable-answer", "h1"],
          },
          headline: post.heading,
          description,
          image: [seo.image],
          url: canonical,
          inLanguage: "en",
          datePublished: post.published,
          dateModified: post.updated,
          articleSection: post.category,
          keywords: seo.keywords,
          author: {
            "@type": "Organization",
            "@id": "https://doseroutine.com/#organization",
            name: BLOG_SITE.name,
            url: BLOG_SITE.base,
          },
          publisher: {
            "@type": "Organization",
            "@id": "https://doseroutine.com/#organization",
            name: BLOG_SITE.name,
            logo: { "@type": "ImageObject", url: BLOG_SITE.logo },
          },
          citation: (post.refs ?? []).map((r) => ({
            "@type": "ScholarlyArticle",
            name: r.cite,
            url: r.url,
          })),
          reviewedBy: {
            "@type": "Organization",
            "@id": "https://doseroutine.com/#organization",
            name: BLOG_SITE.name,
            url: BLOG_SITE.base,
          },
          lastReviewed: post.updated,

          mainEntityOfPage: { "@type": "WebPage", "@id": canonical },
        }),
      },
      ...((post.faqs ?? []).length
        ? [
            {
              type: "application/ld+json",
              children: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "@id": `${canonical}#faq`,
                url: `${canonical}#faq`,
                inLanguage: "en",
                mainEntity: post.faqs.map((f) => ({
                  "@type": "Question",
                  "@id": `${canonical}#${faqAnchorId(f.q)}`,
                  name: f.q,
                  url: `${canonical}#${faqAnchorId(f.q)}`,
                  answerCount: 1,
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: f.a,
                    url: `${canonical}#${faqAnchorId(f.q)}`,
                    inLanguage: "en",
                  },
                })),
              }),
            },
          ]
        : []),
      {
        type: "application/ld+json",
        children: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: BLOG_SITE.name, item: `${BLOG_SITE.base}/` },
            {
              "@type": "ListItem",
              position: 2,
              name: "Research & Updates",
              item: `${BLOG_SITE.base}/blog`,
            },
            { "@type": "ListItem", position: 3, name: post.heading, item: canonical },
          ],
        }),
      },
    ],
  };
}
