// AUTO-GENERATED by scripts/generate-blog-og.py — do not edit by hand.
// Slugs that have a rendered card at public/og/blog/<slug>.png.
export const BLOG_OG_CARD_SLUGS = new Set<string>([
  "best-time-of-day-to-take-a-weekly-glp-1-injection",
  "glp-1-injection-site-rotation-schedule",
  "glp-1-muscle-loss-myostatin-combinations",
  "how-long-does-reconstituted-peptide-last-in-the-fridge",
  "how-much-bacteriostatic-water-for-10mg-retatrutide",
  "how-much-protein-while-on-a-glp-1",
  "klotho-partial-reprogramming-first-human-trials",
  "metformin-and-glp-1-together-what-changes",
  "missed-weekly-glp-1-dose-what-to-do",
  "orforglipron-foundayo-oral-glp-1",
  "retatrutide-triumph-phase-3-results",
  "signs-a-peptide-vial-has-gone-bad",
  "tirzepatide-mg-to-units-on-an-insulin-syringe",
  "when-will-orforglipron-be-available",
]);
