/**
 * Suggested exercise / activity names per workout type.
 *
 * These power the autocomplete list in the workout sheet. They are only
 * suggestions — any free-text name is still accepted.
 */

import { workoutFamily, type WorkoutFamily, type WorkoutType } from "./workout-types";

const BY_TYPE: Partial<Record<WorkoutType, string[]>> = {
  strength: [
    "Back squat",
    "Front squat",
    "Deadlift",
    "Romanian deadlift",
    "Bench press",
    "Incline dumbbell press",
    "Overhead press",
    "Barbell row",
    "Lat pulldown",
    "Seated cable row",
    "Pull-up",
    "Dip",
    "Leg press",
    "Leg curl",
    "Leg extension",
    "Hip thrust",
    "Lunge",
    "Bulgarian split squat",
    "Calf raise",
    "Bicep curl",
    "Triceps pushdown",
    "Lateral raise",
    "Face pull",
    "Cable fly",
    "Plank",
    "Hanging leg raise",
    "Ab wheel rollout",
    "Pallof press",
    "Dead bug",
    "Bird dog",
    "Russian twist",
  ],
  bodyweight: [
    "Push-up",
    "Pull-up",
    "Chin-up",
    "Dip",
    "Air squat",
    "Pistol squat",
    "Lunge",
    "Glute bridge",
    "Plank",
    "Side plank",
    "Hollow hold",
    "Dead bug",
    "Bird dog",
    "Bicycle crunch",
    "Reverse crunch",
    "Flutter kicks",
    "V-up",
    "Superman hold",
    "Bear crawl hold",
    "Russian twist",
    "Burpee",
    "Mountain climber",
    "Inverted row",
    "Nordic curl",
    "Handstand hold",
  ],
  crossfit: [
    "Thruster",
    "Clean & jerk",
    "Snatch",
    "Wall ball",
    "Box jump",
    "Toes to bar",
    "Double under",
    "Kettlebell swing",
    "Burpee",
    "Rowing intervals",
    "Assault bike",
    "Devil press",
  ],
  kettlebell: [
    "Kettlebell swing",
    "Goblet squat",
    "Turkish get-up",
    "Clean & press",
    "Snatch",
    "Front rack carry",
    "Farmer carry",
    "Windmill",
    "Halo",
  ],
  hiit: [
    "Sprint interval",
    "Burpee",
    "Jump squat",
    "Mountain climber",
    "Battle ropes",
    "Box jump",
    "Kettlebell swing",
    "Assault bike sprint",
    "Rowing sprint",
  ],
  run: [
    "Easy run",
    "Tempo run",
    "Interval repeats",
    "Long run",
    "Recovery jog",
    "Hill repeats",
    "Fartlek",
  ],
  trail_run: ["Trail easy run", "Hill repeats", "Long trail run", "Technical descent"],
  bike: ["Endurance ride", "Tempo ride", "Interval ride", "Hill climb", "Recovery spin", "Commute"],
  spin: ["Spin class", "Threshold intervals", "Sprint intervals", "Endurance ride"],
  row: ["Steady row", "500m repeats", "2k test", "Pyramid intervals"],
  swim: [
    "Freestyle laps",
    "Backstroke",
    "Breaststroke",
    "Butterfly",
    "Kick set",
    "Pull set",
    "Interval set",
  ],
  walk: ["Easy walk", "Brisk walk", "Incline treadmill walk", "Rucking"],
  hike: ["Trail hike", "Summit hike", "Weighted hike"],
  elliptical: ["Steady state", "Interval set", "Hill program"],
  stairs: ["Steady climb", "Interval climb", "Stair sprints"],
  ski_erg: ["Steady ski", "500m repeats", "Interval set"],
  jump_rope: ["Single unders", "Double unders", "Interval rounds", "Criss-cross"],
  yoga: [
    // Foundations
    "Mountain pose",
    "Standing forward fold",
    "Downward dog",
    "Low lunge",
    "Chair pose",
    "Tree pose",
    "Cat-cow",
    "Child's pose",
    "Cobra pose",
    "Sphinx pose",
    "Bridge pose",
    "Butterfly pose",
    "Seated forward fold",
    // Intermediate
    "Warrior I",
    "Warrior II",
    "Warrior III",
    "Triangle pose",
    "Extended side angle",
    "Chaturanga",
    "Upward dog",
    "Boat pose",
    "Seated twist",
    "Camel pose",
    "Pigeon pose",
    // Advanced
    "Half moon pose",
    "Dancer pose",
    "Eagle pose",
    "Crow pose",
    "Wheel pose",
    "Headstand",
    // Rest & flows
    "Legs up the wall",
    "Corpse pose",
    "Sun salutations",
    "Vinyasa flow",
    "Hatha",
    "Yin",
    "Power yoga",
    "Hip openers",
    "Restorative",
  ],

  pilates: [
    "Hundred",
    "Roll-up",
    "Single leg stretch",
    "Teaser",
    "Swan",
    "Leg circles",
    "Side kick series",
    "Reformer",
    "Mat pilates",
    "Core series",
  ],
  mobility: [
    "Hip mobility",
    "Shoulder mobility",
    "Thoracic rotations",
    "Ankle mobility",
    "Foam rolling",
    "Cat-cow",
    "Chest opener",
    "90/90 hip stretch",
    "World's greatest stretch",
    "Bird dog",
    "Dead bug",
  ],
  stretching: [
    "Hamstring stretch",
    "Hip flexor stretch",
    "Quad stretch",
    "Seated forward fold",
    "Pigeon pose",
    "Chest opener",
    "Child's pose",
    "Cat-cow",
    "Figure-four stretch",
    "Lying spinal twist",
    "Calf stretch",
    "90/90 hip stretch",
    "World's greatest stretch",
    "Full body stretch",
  ],
  breathwork: ["Box breathing", "Wim Hof rounds", "Nasal breathing", "Diaphragmatic breathing"],
  recovery: [
    "Sauna",
    "Cold plunge",
    "Contrast therapy",
    "Massage",
    "Compression boots",
    "Easy walk",
  ],
  martial_arts: [
    "BJJ rolling",
    "Muay Thai pads",
    "Judo drills",
    "Karate kata",
    "Sparring",
    "Technique drills",
  ],
  boxing: [
    "Jab",
    "Cross",
    "Hook",
    "Uppercut",
    "Shadow boxing",
    "Heavy bag",
    "Pad work",
    "Speed bag",
    "Footwork drills",
    "Sparring",
  ],
  climbing: ["Bouldering", "Top rope", "Lead climbing", "Hangboard", "Campus board", "Traversing"],
  dance: ["Hip hop", "Ballet barre", "Salsa", "Zumba", "Contemporary", "Freestyle"],
  racquet: ["Tennis match", "Tennis drills", "Pickleball", "Padel", "Squash", "Badminton"],
  team_sport: ["Soccer", "Basketball", "Volleyball", "Hockey", "Football", "Rugby", "Softball"],
  golf: ["18 holes", "9 holes", "Driving range", "Short game practice", "Putting"],
  surf_paddle: ["Surf session", "Paddleboard", "Kayak", "Outrigger"],
  sport: ["Skiing", "Snowboarding", "Skating", "Horse riding", "Fencing", "Other sport"],
};

const BY_FAMILY: Record<WorkoutFamily, string[]> = {
  strength: ["Warm-up", "Accessory circuit", "Core finisher"],
  cardio: ["Warm-up", "Main set", "Cool down"],
  mindbody: ["Warm-up", "Main flow", "Cool down"],
  sport: ["Warm-up", "Drills", "Game / session", "Cool down"],
  other: ["Warm-up", "Main set", "Cool down"],
};

/** Suggested activity names for a workout type, most relevant first. */
export function exerciseOptions(type: string | null | undefined): string[] {
  const specific = BY_TYPE[(type ?? "other") as WorkoutType] ?? [];
  const generic = BY_FAMILY[workoutFamily(type)] ?? [];
  const seen = new Set<string>();
  return [...specific, ...generic].filter((name) => {
    const key = name.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}
