/**
 * The everyday foods that show up in most scans.
 *
 * Pre-importing these from USDA means the common case never waits on an
 * external API — and a USDA outage can't degrade a normal meal scan.
 */
export const COMMON_FOOD_SEEDS: string[] = [
  // protein
  "chicken breast, cooked, roasted",
  "chicken thigh, cooked",
  "turkey breast, cooked",
  "ground beef, 90% lean, cooked",
  "beef steak, cooked",
  "pork chop, cooked",
  "bacon, cooked",
  "ham, sliced",
  "salmon, cooked",
  "tuna, canned in water",
  "tilapia, cooked",
  "shrimp, cooked",
  "cod, cooked",
  "egg, whole, cooked",
  "egg white, cooked",
  "tofu, firm",
  "tempeh",
  "protein powder, whey",
  // dairy
  "milk, whole",
  "milk, 2% fat",
  "milk, skim",
  "greek yogurt, plain, nonfat",
  "yogurt, plain, whole milk",
  "cheddar cheese",
  "mozzarella cheese",
  "parmesan cheese",
  "cottage cheese, lowfat",
  "cream cheese",
  "butter, salted",
  "heavy cream",
  // grains and starch
  "white rice, cooked",
  "brown rice, cooked",
  "quinoa, cooked",
  "pasta, cooked",
  "whole wheat pasta, cooked",
  "bread, whole wheat",
  "bread, white",
  "bagel, plain",
  "tortilla, flour",
  "tortilla, corn",
  "oats, cooked",
  "oats, dry",
  "cereal, corn flakes",
  "granola",
  "couscous, cooked",
  "potato, baked",
  "sweet potato, baked",
  "french fries",
  "corn, sweet, cooked",
  // legumes
  "black beans, cooked",
  "pinto beans, cooked",
  "chickpeas, cooked",
  "lentils, cooked",
  "kidney beans, cooked",
  "edamame, cooked",
  "hummus",
  "peanut butter",
  "almond butter",
  // vegetables
  "broccoli, cooked",
  "broccoli, raw",
  "spinach, raw",
  "spinach, cooked",
  "kale, raw",
  "carrots, raw",
  "green beans, cooked",
  "asparagus, cooked",
  "brussels sprouts, cooked",
  "cauliflower, cooked",
  "zucchini, cooked",
  "bell pepper, raw",
  "cucumber, raw",
  "tomato, raw",
  "onion, raw",
  "mushrooms, raw",
  "lettuce, romaine",
  "cabbage, raw",
  "peas, green, cooked",
  "avocado, raw",
  // fruit
  "apple, raw",
  "banana, raw",
  "orange, raw",
  "strawberries, raw",
  "blueberries, raw",
  "raspberries, raw",
  "grapes, raw",
  "pineapple, raw",
  "mango, raw",
  "watermelon, raw",
  "peach, raw",
  "pear, raw",
  "cherries, raw",
  "kiwi, raw",
  "raisins",
  "dates, medjool",
  // nuts, seeds, fats
  "almonds",
  "walnuts",
  "cashews",
  "pistachios",
  "peanuts",
  "chia seeds",
  "flaxseed",
  "pumpkin seeds",
  "sunflower seeds",
  "olive oil",
  "coconut oil",
  "mayonnaise",
  // prepared and snacks
  "pizza, cheese",
  "cheeseburger",
  "burrito, bean and cheese",
  "sushi roll",
  "macaroni and cheese",
  "chicken nuggets",
  "soup, chicken noodle",
  "chili con carne",
  "pancakes",
  "waffle",
  "muffin, blueberry",
  "chocolate chip cookie",
  "brownie",
  "ice cream, vanilla",
  "dark chocolate",
  "potato chips",
  "tortilla chips",
  "popcorn, air popped",
  "pretzels",
  "protein bar",
  // drinks and condiments
  "orange juice",
  "apple juice",
  "coffee, brewed",
  "beer, regular",
  "wine, red",
  "cola",
  "sports drink",
  "ketchup",
  "mustard",
  "soy sauce",
  "ranch dressing",
  "barbecue sauce",
  "honey",
  "maple syrup",
  "sugar, granulated",
];
