import js from "@eslint/js";
import eslintPluginPrettier from "eslint-plugin-prettier/recommended";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "dist",
      ".output",
      ".vinxi",
      ".nitro",
      // Native shells and vendored Capacitor/SPM packages are not our source.
      "ios",
      "android",
      "playwright-report",
      "test-results",
      "public",
      "src/routeTree.gen.ts",
      // Auto-generated by the backend integration and rewritten wholesale on
      // every regeneration. Matching the directory (not one file, not a
      // content fingerprint) keeps the exclusion stable no matter how the
      // generator reshapes or renames these files.
      "src/integrations/supabase/**",
    ],
  },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Hook order/placement bugs are crashes in production, not style nits.
      // A duplicated block that ends up calling a hook inside useMemo/useEffect
      // (the /food "Cannot access 'c' before initialization" crash) is caught here.
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
      // Temporal-dead-zone guards: referencing a const/let (e.g. a useMemo
      // result) before its declaration only blows up at runtime otherwise.
      // Warning-level repo-wide because ~345 legacy call-order sites are safe
      // closures; new code should not add any.
      "no-use-before-define": "off",
      "@typescript-eslint/no-use-before-define": [
        "warn",
        {
          functions: false,
          classes: false,
          variables: true,
          enums: true,
          typedefs: false,
          ignoreTypeReferences: true,
          allowNamedExports: false,
        },
      ],
      // Duplicated blocks from bad merges/edits.
      "no-dupe-class-members": "off",
      "@typescript-eslint/no-dupe-class-members": "error",
      "no-redeclare": "off",
      "@typescript-eslint/no-redeclare": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-duplicate-case": "error",
      // Type-only + value imports from one module are legitimate, so this
      // stays a warning that still surfaces accidental double blocks.
      "no-duplicate-imports": ["warn", { includeExports: false }],

      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-unreachable": "error",
      "no-constant-binary-expression": "error",

      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "server-only",
              message:
                "TanStack Start does not use the Next.js `server-only` package. Rename the module to `*.server.ts` or mark it with `@tanstack/react-start/server-only`.",
            },
          ],
        },
      ],
      // Fast-refresh ergonomics only (never a correctness bug). This repo
      // deliberately colocates variant maps, helpers and small sub-components
      // next to the component that uses them, so the rule fires ~80 times on
      // intentional code and would block the `--max-warnings=0` gate.
      "react-refresh/only-export-components": "off",
      "@typescript-eslint/no-unused-vars": "off",
      // Known backlog (~181 sites), tracked for a separate cleanup pass. Kept
      // visible as a warning so the CI lint gate can enforce real errors today.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  eslintPluginPrettier,
  {
    // Integration-managed MCP routes are regenerated verbatim, so formatting
    // them locally is churn the tooling immediately undoes.
    files: [
      "src/routes/mcp.ts",
      "**/list-tools.ts",
      "**/invoke-tool/*.ts",
      "**/oauth-protected-resource.ts",
    ],
    rules: { "prettier/prettier": "off" },
  },
);
