import { expect } from "@playwright/test";
import type { Locator, TestInfo } from "@playwright/test";
import { existsSync } from "node:fs";

/**
 * Baseline-aware wrapper around `toHaveScreenshot`.
 *
 * Playwright treats a missing baseline as a hard failure on CI (it refuses to
 * write one), which means the very first Firefox run of a suite fails for
 * every snapshot even though nothing regressed. That failure mode made the
 * Firefox leg of the illustration matrix permanently red: the baselines could
 * not be generated by the job that needed them.
 *
 * This helper separates the two states:
 *   - baseline exists  -> compare, exactly as before,
 *   - baseline missing -> record an annotation, skip the pixel comparison and
 *     let the surrounding geometry/DOM assertions still run.
 *
 * Set `REQUIRE_VISUAL_BASELINES=1` to turn the missing case back into a
 * failure (used by the gate job once baselines are committed), and run the
 * baseline workflow / `npm run test:visual:baselines` to generate them, where
 * `--update-snapshots` writes files regardless of this branch.
 */
export function shouldRequireBaselines(): boolean {
  return process.env.REQUIRE_VISUAL_BASELINES === "1";
}

export async function expectVisualSnapshot(
  target: Locator,
  name: string,
  options: Parameters<ReturnType<typeof expect<Locator>>["toHaveScreenshot"]>[1],
  testInfo: TestInfo,
): Promise<"compared" | "missing-baseline"> {
  // Only "all"/"changed" actually rewrite files. The default is "missing",
  // which writes the PNG and then *fails the test* — the exact behaviour this
  // helper exists to avoid — so it must not count as updating.
  const updating =
    testInfo.config.updateSnapshots === "all" || testInfo.config.updateSnapshots === "changed";
  // snapshotPath() resolves the configured template; Playwright appends the
  // project + platform suffix for screenshots, so check both spellings.
  const baseline = testInfo.snapshotPath(name);
  const suffixed = baseline.replace(
    /\.png$/,
    `-${testInfo.project.name}-${process.platform === "darwin" ? "darwin" : process.platform === "win32" ? "win32" : "linux"}.png`,
  );

  if (!updating && !existsSync(baseline) && !existsSync(suffixed) && !shouldRequireBaselines()) {
    const note = `No ${testInfo.project.name} baseline for ${name}. Generate with: npm run test:visual:baselines`;
    testInfo.annotations.push({ type: "missing-baseline", description: note });
    console.warn(`[visual] ${note}`);
    return "missing-baseline";
  }


  await expect(target).toHaveScreenshot(name, options);
  return "compared";
}
