import type { WomensCompoundMeta } from "@/components/womens-compound-article";

/**
 * Head-only metadata for every women's-health article.
 * Generated from the *-content.ts modules. Routes import from here so the
 * full article bodies stay in each route's own lazily-loaded chunk.
 */
export const WOMENS_META = {
  "b6-luteal": {
    slug: "b6-luteal",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "Vitamin B6 (Luteal Phase)",
    h1: "Vitamin B6 for PMS, Luteal Mood, and Contraceptive Support",
    lastReviewed: "2026-07-27",
  },
  "coq10-fertility": {
    slug: "coq10-fertility",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "CoQ10 (Egg Quality)",
    h1: "CoQ10 for Egg Quality: Evidence, Dosage & IVF Interactions",
    lastReviewed: "2026-07-27",
  },
  "d-chiro-inositol": {
    slug: "d-chiro-inositol",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "D-Chiro-Inositol",
    h1: "D-Chiro-Inositol for Women: When to Use It (and When Not To)",
    lastReviewed: "2026-07-27",
  },
  "folate-vs-folic-acid": {
    slug: "folate-vs-folic-acid",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "Folate vs Folic Acid",
    h1: "Folate vs Folic Acid: When the Difference Actually Matters",
    lastReviewed: "2026-07-27",
  },
  "iron-cycle": {
    slug: "iron-cycle",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "Iron (Cycle Context)",
    h1: "Iron for Women: Heavy Periods, Ferritin Targets, and Thyroid Timing",
    lastReviewed: "2026-07-27",
  },
  "myo-inositol": {
    slug: "myo-inositol",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "Myo-Inositol",
    h1: "Myo-Inositol for Women: PCOS, Fertility, and Insulin Sensitivity",
    lastReviewed: "2026-07-27",
  },
  "vitamin-d-fertility": {
    slug: "vitamin-d-fertility",
    hubSlug: "fertility-cycle",
    hubTitle: "Fertility & Cycle Support",
    compoundName: "Vitamin D (Fertility)",
    h1: "Vitamin D for Fertility: What Deficiency Actually Costs You",
    lastReviewed: "2026-07-27",
  },
  "collagen-peptides-women": {
    slug: "collagen-peptides-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Collagen Peptides",
    h1: "Collagen Peptides for Women: Evidence, Dosage & Interactions",
    lastReviewed: "2026-07-27",
  },
  "coq10-women": {
    slug: "coq10-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "CoQ10 (Ubiquinol)",
    h1: "CoQ10 (Ubiquinol) for Women: Statin Support, Heart & Fertility",
    lastReviewed: "2026-07-27",
  },
  "creatine-women": {
    slug: "creatine-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Creatine Monohydrate (for women)",
    h1: "Creatine for Women: Muscle, Bone, Brain & Perimenopause",
    lastReviewed: "2026-07-27",
  },
  "magnesium-glycinate-women": {
    slug: "magnesium-glycinate-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Magnesium Glycinate (for women)",
    h1: "Magnesium Glycinate for Women: Sleep, Cramps, and Longevity",
    lastReviewed: "2026-07-27",
  },
  "nad-precursors": {
    slug: "nad-precursors",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "NAD+ Precursors (NMN vs NR)",
    h1: "NMN vs NR for Women: What the Human Data Actually Shows",
    lastReviewed: "2026-07-27",
  },
  "nmn-women": {
    slug: "nmn-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "NMN (Nicotinamide Mononucleotide)",
    h1: "NMN for Women: Evidence, Dosage & Interactions",
    lastReviewed: "2026-07-27",
  },
  "omega-3-women": {
    slug: "omega-3-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Omega-3 (EPA/DHA) for Women",
    h1: "Omega-3 for Women: Heart, Brain, Perimenopause Mood, and Interactions",
    lastReviewed: "2026-07-27",
  },
  "resveratrol-women": {
    slug: "resveratrol-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Resveratrol",
    h1: "Resveratrol for Women: Sirtuin Hype vs Human Evidence",
    lastReviewed: "2026-07-27",
  },
  "spermidine-women": {
    slug: "spermidine-women",
    hubSlug: "longevity",
    hubTitle: "Longevity for Women",
    compoundName: "Spermidine",
    h1: "Spermidine for Women: Autophagy, Longevity Claims & Interactions",
    lastReviewed: "2026-07-27",
  },
  "black-cohosh": {
    slug: "black-cohosh",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Black Cohosh",
    h1: "Black Cohosh for Women: Evidence, Dosage & Interactions",
    lastReviewed: "2026-07-27",
  },
  "dhea-women": {
    slug: "dhea-women",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "DHEA",
    h1: "DHEA for Women: Evidence, Uses & Interactions",
    lastReviewed: "2026-07-27",
  },
  "estradiol-hrt": {
    slug: "estradiol-hrt",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Estradiol / HRT",
    h1: "Estradiol & HRT for Women: Interactions Overview (Not Dosing Advice)",
    lastReviewed: "2026-07-27",
  },
  "evening-primrose-oil": {
    slug: "evening-primrose-oil",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Evening Primrose Oil",
    h1: "Evening Primrose Oil for Women: Evidence & Interactions",
    lastReviewed: "2026-07-27",
  },
  "maca-menopause": {
    slug: "maca-menopause",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Maca (Menopause)",
    h1: "Maca for Menopause: Evidence & Interactions",
    lastReviewed: "2026-07-27",
  },
  "progesterone-women": {
    slug: "progesterone-women",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Progesterone",
    h1: "Progesterone for Women: Interactions Overview (Not Dosing Advice)",
    lastReviewed: "2026-07-27",
  },
  "red-clover": {
    slug: "red-clover",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Red Clover",
    h1: "Red Clover for Women: Evidence & Interactions",
    lastReviewed: "2026-07-27",
  },
  "soy-isoflavones": {
    slug: "soy-isoflavones",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Soy Isoflavones",
    h1: "Soy Isoflavones (Phytoestrogens) for Women: Evidence & Interactions",
    lastReviewed: "2026-07-27",
  },
  vitex: {
    slug: "vitex",
    hubSlug: "menopause-hormones",
    hubTitle: "Menopause & Hormone Balance",
    compoundName: "Vitex (Chasteberry)",
    h1: "Vitex (Chasteberry) for Women: Evidence & Interactions",
    lastReviewed: "2026-07-27",
  },
  "ashwagandha-women": {
    slug: "ashwagandha-women",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "Ashwagandha (for women)",
    h1: "Ashwagandha for Women: Stress, Sleep, Libido, and Thyroid Cautions",
    lastReviewed: "2026-07-27",
  },
  "l-arginine-women": {
    slug: "l-arginine-women",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "L-Arginine (for women)",
    h1: "L-Arginine for Women: Blood Flow, Libido, and Interactions",
    lastReviewed: "2026-07-27",
  },
  "maca-libido": {
    slug: "maca-libido",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "Maca (libido context)",
    h1: "Maca for Women's Libido: Evidence, Dosage & Interactions",
    lastReviewed: "2026-07-27",
  },
  "testosterone-women": {
    slug: "testosterone-women",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "Low-dose Testosterone (women)",
    h1: "Low-Dose Testosterone for Women: Interaction & Safety Reference",
    lastReviewed: "2026-07-27",
  },
  "tribulus-women": {
    slug: "tribulus-women",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "Tribulus Terrestris (women)",
    h1: "Tribulus Terrestris for Women: What the Evidence Actually Says",
    lastReviewed: "2026-07-27",
  },
  "vaginal-probiotics": {
    slug: "vaginal-probiotics",
    hubSlug: "sexual-health",
    hubTitle: "Sexual Health & Libido for Women",
    compoundName: "Vaginal Probiotics",
    h1: "Vaginal Probiotics: L. crispatus, L. rhamnosus & Recurrent UTI/BV",
    lastReviewed: "2026-07-27",
  },
} satisfies Record<string, WomensCompoundMeta>;
