import { useEffect, useMemo, useState } from "react";
import { Mail, MessageSquare, X, Copy, Check, FileDown } from "lucide-react";
// jsPDF is ~450kB; load it only when the user actually asks for a PDF.
async function downloadInteractionPdf(args: { stackNames: string[]; pairs: unknown[] }) {
  const mod = await import("@/lib/clinician-pdf");
  return (mod.downloadInteractionPdf as (a: typeof args) => void)(args);
}
import type { Database } from "@/integrations/supabase/types";

type Severity = Database["public"]["Enums"]["severity_enum"];

export type SharePair = {
  a: string;
  b: string;
  severity: Severity;
  recommendation: string;
  mechanism: string;
  sources: string[]; // "Label|https://..." strings, matching interaction_rules.source_refs
};

type Contact = { email: string; phone: string };
const STORAGE_KEY = "doseroutine:clinician-contact:v1";
const LEGACY_KEY = "sw:clinician-contact:v1";

function loadContact(): Contact {
  if (typeof window === "undefined") return { email: "", phone: "" };
  try {
    let raw = window.localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      const legacy = window.localStorage.getItem(LEGACY_KEY);
      if (legacy) {
        window.localStorage.setItem(STORAGE_KEY, legacy);
        window.localStorage.removeItem(LEGACY_KEY);
        raw = legacy;
      }
    }
    if (!raw) return { email: "", phone: "" };
    const parsed = JSON.parse(raw);
    return { email: parsed.email ?? "", phone: parsed.phone ?? "" };
  } catch {
    return { email: "", phone: "" };
  }
}
function saveContact(c: Contact) {
  try {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(c));
  } catch {
    // Non-critical: safe to ignore.
  }
}

const SEV_LABEL: Record<Severity, string> = {
  avoid: "AVOID",
  caution: "CAUTION",
  note: "Note",
  synergy: "Synergy",
};

export function buildShareSummary(opts: {
  patientLabel?: string;
  stackNames: string[];
  pairs: SharePair[];
}): { subject: string; body: string; short: string } {
  const { patientLabel, stackNames, pairs } = opts;
  const date = new Date().toLocaleDateString();

  const header = patientLabel ? `Name: ${patientLabel}\nDate: ${date}` : `Date: ${date}`;

  const stackLine = stackNames.length > 0 ? `\n\nCurrent stack:\n- ${stackNames.join("\n- ")}` : "";

  const flaggedText =
    pairs.length === 0
      ? "\n\nNo flagged interactions in DoseRoutine's rule set."
      : "\n\nFlagged interactions:\n" +
        pairs
          .map((p, i) => {
            const src =
              p.sources.length > 0
                ? "\n  Sources: " +
                  p.sources
                    .map((s) => {
                      const [label, url] = s.split("|");
                      return url ? `${label} (${url})` : label;
                    })
                    .join("; ")
                : "";
            return `${i + 1}. [${SEV_LABEL[p.severity]}] ${p.a} × ${p.b}
  Recommendation: ${p.recommendation}
  Mechanism: ${p.mechanism}${src}`;
          })
          .join("\n\n");

  const footer =
    "\n\n—\nGenerated by DoseRoutine (https://doseroutine.com). Educational summary, not medical advice. Please review before starting or changing any medication or supplement.";

  const body = header + stackLine + flaggedText + footer;
  const majorCount = pairs.filter((p) => p.severity === "avoid" || p.severity === "caution").length;
  const subject = `DoseRoutine interaction summary${majorCount > 0 ? ` — ${majorCount} major flag${majorCount === 1 ? "" : "s"}` : ""}`;

  // SMS-friendly short form (single message-ish).
  const short =
    pairs.length === 0
      ? `DoseRoutine summary (${date}): ${stackNames.length} items in my stack, no flagged interactions. Can you review? — via doseroutine.com`
      : `DoseRoutine summary (${date}): ${pairs.length} flagged interaction${
          pairs.length === 1 ? "" : "s"
        } in my stack (${majorCount} major). Top: ${pairs
          .slice(0, 2)
          .map((p) => `${p.a}×${p.b} [${SEV_LABEL[p.severity]}]`)
          .join("; ")}. Full details to follow by email. — via doseroutine.com`;

  return { subject, body, short };
}

export function ShareWithClinicianButton(props: { stackNames: string[]; pairs: SharePair[] }) {
  const [open, setOpen] = useState(false);
  if (props.stackNames.length === 0) return null;
  return (
    <div className="flex flex-wrap items-center gap-2">
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="tap-target inline-flex h-10 items-center gap-1.5 rounded-lg border border-primary/40 bg-primary px-3 text-xs font-semibold text-primary-foreground hover:bg-[color:var(--primary-hover)]"
      >
        <Mail className="h-3.5 w-3.5" /> Share summary
      </button>
      <button
        type="button"
        onClick={() =>
          downloadInteractionPdf({
            stackNames: props.stackNames,
            pairs: props.pairs,
          })
        }
        className="tap-target inline-flex h-10 items-center gap-1.5 rounded-lg border border-border bg-background px-3 text-xs font-semibold text-foreground hover:bg-card"
      >
        <FileDown className="h-3.5 w-3.5" /> Download PDF
      </button>
      {open && (
        <ShareSheet
          stackNames={props.stackNames}
          pairs={props.pairs}
          onClose={() => setOpen(false)}
        />
      )}
    </div>
  );
}

function ShareSheet({
  stackNames,
  pairs,
  onClose,
}: {
  stackNames: string[];
  pairs: SharePair[];
  onClose: () => void;
}) {
  const [contact, setContact] = useState<Contact>(() => loadContact());
  const [copied, setCopied] = useState<"email" | "sms" | null>(null);
  useEffect(() => {
    saveContact(contact);
  }, [contact]);

  const { subject, body, short } = useMemo(
    () => buildShareSummary({ stackNames, pairs }),
    [stackNames, pairs],
  );

  const mailtoHref = `mailto:${encodeURIComponent(contact.email)}?subject=${encodeURIComponent(
    subject,
  )}&body=${encodeURIComponent(body)}`;
  // iOS uses `&body=`; Android historically used `?body=`. `sms:?&body=` works
  // on both; recipient is optional so users can pick from contacts.
  const smsHref = `sms:${encodeURIComponent(contact.phone)}${contact.phone ? "?" : "?"}&body=${encodeURIComponent(
    short,
  )}`;

  async function copy(text: string, kind: "email" | "sms") {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(kind);
      setTimeout(() => setCopied(null), 1500);
    } catch {
      // Non-critical: safe to ignore.
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/50 sm:items-center">
      <div className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-t-2xl bg-background sm:rounded-2xl">
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-background px-5 py-4">
          <h2 className="font-display text-lg font-semibold">Share summary</h2>
          <button
            onClick={onClose}
            aria-label="Close"
            className="grid h-11 w-11 place-items-center rounded-lg text-muted-foreground hover:bg-card"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="space-y-5 px-5 py-5 text-sm">
          <div>
            <label
              className="text-xs font-semibold uppercase tracking-wider text-muted-foreground"
              htmlFor="clin-email"
            >
              Recipient email (optional)
            </label>
            <input
              id="clin-email"
              type="email"
              inputMode="email"
              autoComplete="email"
              placeholder="pharmacist@clinic.com"
              value={contact.email}
              onChange={(e) => setContact((c) => ({ ...c, email: e.target.value }))}
              className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm"
            />
          </div>
          <div>
            <label
              className="text-xs font-semibold uppercase tracking-wider text-muted-foreground"
              htmlFor="clin-phone"
            >
              Recipient mobile (optional)
            </label>
            <input
              id="clin-phone"
              type="tel"
              inputMode="tel"
              autoComplete="tel"
              placeholder="+1 555 123 4567"
              value={contact.phone}
              onChange={(e) => setContact((c) => ({ ...c, phone: e.target.value }))}
              className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2 text-sm"
            />
            <p className="mt-1 text-[11px] text-muted-foreground">
              Saved on this device only. Leave blank to pick a contact when your Mail / Messages app
              opens.
            </p>
          </div>

          <div className="grid grid-cols-1 gap-2 sm:grid-cols-3">
            <a
              href={mailtoHref}
              className="tap-target inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground hover:bg-[color:var(--primary-hover)]"
            >
              <Mail className="h-4 w-4" /> Open in Mail
            </a>
            <a
              href={smsHref}
              className="tap-target inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-border bg-background px-4 text-sm font-semibold text-foreground hover:bg-card"
            >
              <MessageSquare className="h-4 w-4" /> Open in Messages
            </a>
            <button
              type="button"
              onClick={() => downloadInteractionPdf({ stackNames, pairs })}
              className="tap-target inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-border bg-background px-4 text-sm font-semibold text-foreground hover:bg-card"
            >
              <FileDown className="h-4 w-4" /> Download PDF
            </button>
          </div>

          <details className="rounded-xl border border-border bg-card/40 p-3">
            <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Preview email
            </summary>
            <div className="mt-2 space-y-2">
              <div className="text-xs text-muted-foreground">
                Subject: <span className="text-foreground">{subject}</span>
              </div>
              <pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded-lg bg-background p-3 text-[11px] leading-snug text-foreground">
                {body}
              </pre>
              <button
                type="button"
                onClick={() => copy(`${subject}\n\n${body}`, "email")}
                className="tap-target inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-[11px] font-semibold text-foreground hover:bg-card"
              >
                {copied === "email" ? (
                  <Check className="h-3.5 w-3.5" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                {copied === "email" ? "Copied" : "Copy email text"}
              </button>
            </div>
          </details>

          <details className="rounded-xl border border-border bg-card/40 p-3">
            <summary className="cursor-pointer text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Preview SMS
            </summary>
            <div className="mt-2 space-y-2">
              <pre className="max-h-40 overflow-auto whitespace-pre-wrap rounded-lg bg-background p-3 text-[11px] leading-snug text-foreground">
                {short}
              </pre>
              <button
                type="button"
                onClick={() => copy(short, "sms")}
                className="tap-target inline-flex h-9 items-center gap-1.5 rounded-lg border border-border px-3 text-[11px] font-semibold text-foreground hover:bg-card"
              >
                {copied === "sms" ? (
                  <Check className="h-3.5 w-3.5" />
                ) : (
                  <Copy className="h-3.5 w-3.5" />
                )}
                {copied === "sms" ? "Copied" : "Copy SMS text"}
              </button>
            </div>
          </details>

          <p className="text-[11px] text-muted-foreground">
            Uses your device's default Mail and Messages apps. Nothing is sent from DoseRoutine —
            you review and send.
          </p>
        </div>
      </div>
    </div>
  );
}
