/**
 * Regenerate the evidence-based goal tagging audit + migration.
 *
 *   bun run scripts/audit-goal-tags.ts            # report only
 *   bun run scripts/audit-goal-tags.ts --sql      # also write the migration body
 *
 * Reads every compound and its written sections, scores each goal with
 * src/lib/goal-evidence.ts, and reports which tags are evidence-backed.
 * No facts are invented: a tag is only proposed when the compound's own
 * benefits/evidence prose contains the goal's evidence phrases.
 */
import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "node:fs";
import { deriveGoalTags } from "../src/lib/goal-evidence";

const url = process.env["VITE_SUPABASE_URL"]!;
const key = process.env["VITE_SUPABASE_PUBLISHABLE_KEY"]!;
const supabase = createClient(url, key, { auth: { persistSession: false } });

type Row = {
  id: string;
  slug: string;
  name: string;
  category: string | null;
  goal_tags: string[] | null;
  education_md: string | null;
};

async function main() {
  const compounds: Row[] = [];
  for (let from = 0; ; from += 500) {
    const { data, error } = await supabase
      .from("compounds")
      .select("id,slug,name,category,goal_tags,education_md")
      .order("slug")
      .range(from, from + 499);
    if (error) throw error;
    compounds.push(...(data as Row[]));
    if (!data || data.length < 500) break;
  }

  const contentById = new Map<string, Record<string, string | null>>();
  for (let from = 0; ; from += 500) {
    const { data, error } = await supabase
      .from("compound_content")
      .select("compound_id,benefits_md,evidence_md,mechanism_md,overview_md")
      .range(from, from + 499);
    if (error) throw error;
    for (const r of data ?? []) contentById.set((r as any).compound_id, r as any);
    if (!data || data.length < 500) break;
  }

  const lines: string[] = [
    "# Goal tagging audit (evidence-derived)",
    "",
    `Generated by \`scripts/audit-goal-tags.ts\` from ${compounds.length} compounds.`,
    "Tags are derived from each compound's own benefits/evidence prose — see",
    "`src/lib/goal-evidence.ts` for the phrase lists and scoring.",
    "",
    "| Compound | Current tags | Proposed tags | Added | Removed |",
    "| --- | --- | --- | --- | --- |",
  ];
  const updates: string[] = [];
  let changed = 0;

  for (const c of compounds) {
    const content = contentById.get(c.id) ?? {};
    const derived = deriveGoalTags(c.goal_tags, {
      benefitsMd: content["benefits_md"],
      evidenceMd: content["evidence_md"],
      mechanismMd: content["mechanism_md"],
      overviewMd: content["overview_md"],
      educationMd: c.education_md,
    }, 4, c.category);
    const same =
      derived.added.length === 0 && derived.removed.length === 0;
    if (same) continue;
    changed += 1;
    lines.push(
      `| ${c.name} | ${(c.goal_tags ?? []).join(", ") || "—"} | ${derived.tags.join(", ")} | ${derived.added.join(", ") || "—"} | ${derived.removed.join(", ") || "—"} |`,
    );
    const arr = derived.tags.map((t) => `'${t.replace(/'/g, "''")}'`).join(", ");
    updates.push(
      `UPDATE public.compounds SET goal_tags = ARRAY[${arr}]::text[] WHERE slug = '${c.slug}';`,
    );
  }

  lines.splice(4, 0, `${changed} of ${compounds.length} compounds change.`, "");
  writeFileSync("docs/goal-tag-audit.md", lines.join("\n") + "\n");
  console.log(`report: docs/goal-tag-audit.md (${changed} changes)`);

  if (process.argv.includes("--sql")) {
    writeFileSync("docs/goal-tag-retag.sql", updates.join("\n") + "\n");
    console.log(`sql: docs/goal-tag-retag.sql (${updates.length} statements)`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
