#!/usr/bin/env python3
"""Generate a unique 1200x630 OG/Twitter card for every blog post.

Reads slug/heading/category from src/lib/blog-posts.ts and writes
public/og/blog/<slug>.png. Re-run after adding a post:

    python3 scripts/generate-blog-og.py
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from og_card import render_card  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src/lib/blog-posts.ts"
# Long-tail posts live in their own module but need cards just the same.
SRC_LONGTAIL = ROOT / "src/lib/blog-posts-longtail.ts"
OUT = ROOT / "public/og/blog"
def parse_posts(text):
    posts = []
    for block in text.split('\n    slug: "')[1:]:
        slug = block.split('"')[0]
        heading = re.search(r'\n    heading:\s*\n?\s*"((?:[^"\\]|\\.)*)"', block)
        category = re.search(r'\n    category:\s*"([^"]*)"', block)
        if heading:
            posts.append(
                {
                    "slug": slug,
                    "heading": heading.group(1).replace('\\"', '"').replace("\\'", "'"),
                    "category": category.group(1) if category else "Research & Updates",
                }
            )
    return posts


def render(post):
    img = render_card(post["heading"], post["category"], "doseroutine.com/blog")
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{post['slug']}.png"
    img.save(path, optimize=True)
    return path


MANIFEST = ROOT / "src/lib/blog-og-manifest.ts"


def write_manifest(slugs):
    lines = "\n".join(f'  "{s}",' for s in sorted(slugs))
    MANIFEST.write_text(
        "// AUTO-GENERATED by scripts/generate-blog-og.py — do not edit by hand.\n"
        "// Slugs that have a rendered card at public/og/blog/<slug>.png.\n"
        "export const BLOG_OG_CARD_SLUGS = new Set<string>([\n"
        f"{lines}\n"
        "]);\n"
    )
    return MANIFEST


if __name__ == "__main__":
    posts = parse_posts(SRC.read_text())
    seen = {p["slug"] for p in posts}
    for post in parse_posts(SRC_LONGTAIL.read_text()):
        if post["slug"] not in seen:
            posts.append(post)
            seen.add(post["slug"])
    for p in posts:
        print("wrote", render(p).relative_to(ROOT))
    print("wrote", write_manifest(p["slug"] for p in posts).relative_to(ROOT))
