#!/usr/bin/env python3
"""Generate a unique 1200x630 OG/Twitter card for every /articles post.

Reads the first-party drafts in src/content/article-drafts/*.md (frontmatter
`suggested_slug` + the H1) and writes public/og/articles/<slug>.png, plus a
brand fallback card at public/og/articles/default.png used by CMS posts
that ship without a hero image.

Re-run after adding or renaming an article:

    python3 scripts/generate-article-og.py
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from og_card import render_card  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
DRAFTS = ROOT / "src/content/article-drafts"
OUT = ROOT / "public/og/articles"
MANIFEST = ROOT / "src/lib/article-og-manifest.ts"

EYEBROW = "DoseRoutine Articles"
URL_LABEL = "doseroutine.com/articles"


def parse_draft(path: Path):
    text = path.read_text(encoding="utf-8")
    fm = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not fm:
        return None
    meta = {}
    for line in fm.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            meta[k.strip()] = v.strip()
    slug = meta.get("suggested_slug")
    if not slug:
        return None
    h1 = re.search(r"^#\s+(.+)$", text, re.M)
    heading = h1.group(1).strip() if h1 else meta.get("meta_title", slug)
    hero = ROOT / "public" / "articles" / f"hero-{slug}.webp"
    return {"slug": slug, "heading": heading, "hero": hero if hero.exists() else None}


def write_manifest(slugs):
    lines = "\n".join(f'  "{s}",' for s in sorted(slugs))
    MANIFEST.write_text(
        "// AUTO-GENERATED by scripts/generate-article-og.py — do not edit by hand.\n"
        "// Slugs that have a rendered card at public/og/articles/<slug>.png.\n"
        "export const ARTICLE_OG_CARD_SLUGS = new Set<string>([\n"
        f"{lines}\n"
        "]);\n\n"
        '/** Fallback card for /articles pages without their own rendered image. */\n'
        'export const ARTICLE_OG_FALLBACK = "/og/articles/default.png";\n\n'
        "export const ARTICLE_OG_WIDTH = 1200;\nexport const ARTICLE_OG_HEIGHT = 630;\n\n"
        "/** Site-relative card path for a slug, falling back to the brand card. */\n"
        "export function articleOgPath(slug: string): string {\n"
        "  return ARTICLE_OG_CARD_SLUGS.has(slug)\n"
        "    ? `/og/articles/${slug}.png`\n"
        "    : ARTICLE_OG_FALLBACK;\n"
        "}\n",
        encoding="utf-8",
    )


def save_all_formats(img, stem: Path):
    """Write the PNG fallback plus modern WebP/AVIF siblings.

    Social crawlers only reliably read PNG/JPEG, so the .png stays the
    canonical og:image. The .webp/.avif siblings are what the site itself
    serves through <picture>, and the image checks require all three.
    """
    img.save(stem.with_suffix(".png"), optimize=True)
    img.save(stem.with_suffix(".webp"), quality=82, method=6)
    img.save(stem.with_suffix(".avif"), quality=55)
    for ext in (".png", ".webp", ".avif"):
        print("wrote", stem.with_suffix(ext))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    drafts = [d for d in (parse_draft(p) for p in sorted(DRAFTS.glob("*.md"))) if d]
    for draft in drafts:
        img = render_card(draft["heading"], EYEBROW, URL_LABEL, hero=draft["hero"])
        save_all_formats(img, OUT / draft["slug"])

    fallback = render_card(
        "Nutrition, training and protocol guides",
        EYEBROW,
        URL_LABEL,
    )
    save_all_formats(fallback, OUT / "default")

    write_manifest([d["slug"] for d in drafts])
    print("wrote", MANIFEST)


if __name__ == "__main__":
    main()
