#!/usr/bin/env python3
"""Generate a unique branded 1200x630 card for every marketing / tool page.

Sources of truth (parsed, never duplicated):
  src/lib/app-roundups.ts        -> /best-* roundups and /for/* use cases
  src/lib/compound-calculators.ts -> /calculators/* pages

Writes public/og/pages/<slug>.png and regenerates
src/lib/page-og-manifest.ts so the sitemap knows which cards exist.

    python3 scripts/generate-page-og.py
"""
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from og_card import render_card  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public/og/pages"
MANIFEST = ROOT / "src/lib/page-og-manifest.ts"


def blocks(text, start_marker):
    """Split a TS array/record literal into per-entry text blocks."""
    body = text.split(start_marker, 1)[1]
    return body.split('\n    slug: "')[1:]


def entries(text, start_marker, end_marker, eyebrow):
    section = text.split(start_marker, 1)[1].split(end_marker, 1)[0]
    out = []
    for block in section.split('\n    slug: "')[1:]:
        slug = block.split('"')[0]
        h1 = re.search(r'\n    h1: "((?:[^"\\]|\\.)*)"', block)
        if not h1:
            continue
        out.append(
            {
                "slug": slug,
                "heading": h1.group(1).replace('\\"', '"'),
                "eyebrow": eyebrow,
            }
        )
    return out


def collect():
    roundups_src = (ROOT / "src/lib/app-roundups.ts").read_text()
    calculators_src = (ROOT / "src/lib/compound-calculators.ts").read_text()

    pages = []
    pages += entries(roundups_src, "export const ROUNDUPS", "export const ROUNDUP_LIST", "App comparison")
    pages += entries(roundups_src, "export const USE_CASES", "export const USE_CASE_LIST", "Built for")
    pages += entries(
        calculators_src, "export const CALCULATOR_PAGES", "export const CALCULATOR_SLUGS", "Calculator"
    )
    return pages


def write_manifest(slugs):
    lines = "\n".join(f'  "{s}",' for s in sorted(slugs))
    MANIFEST.write_text(
        "// AUTO-GENERATED by scripts/generate-page-og.py — do not edit by hand.\n"
        "// Page slugs that have a rendered card at public/og/pages/<slug>.png.\n"
        "export const PAGE_OG_CARD_SLUGS = new Set<string>([\n"
        f"{lines}\n"
        "]);\n"
    )
    return MANIFEST


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    pages = collect()
    if not pages:
        raise SystemExit("no pages parsed — check the TS source markers")
    for page in pages:
        img = render_card(page["heading"], page["eyebrow"], "doseroutine.com")
        path = OUT / f"{page['slug']}.png"
        img.save(path, optimize=True)
        print("wrote", path.relative_to(ROOT))
    print("wrote", write_manifest(p["slug"] for p in pages).relative_to(ROOT))
