UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'longevity']::text[] WHERE slug = '5-amino-1mq';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'weight-loss']::text[] WHERE slug = '7-keto-dhea';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'acetaminophen';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'acp-105';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'adipotide';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'endurance']::text[] WHERE slug = 'agmatine-sulfate';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'blood-sugar']::text[] WHERE slug = 'ala';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss']::text[] WHERE slug = 'albiglutide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'allopurinol';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'amantadine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'amitriptyline';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'amlodipine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'amoxicillin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'amphetamine-salts';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'anamorelin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'anastrozole-arimidex';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'muscle', 'testosterone']::text[] WHERE slug = 'andarine';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'apigenin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'apixaban';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss', 'cardiovascular']::text[] WHERE slug = 'apple-cider-vinegar';
UPDATE public.compounds SET goal_tags = ARRAY['skin-hair']::text[] WHERE slug = 'argireline';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'armodafinil';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'sleep', 'menopause', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'ashwagandha';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'sleep']::text[] WHERE slug = 'ashwagandha-ksm-66';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'aspirin-low-dose';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'endurance', 'immune', 'skin-hair']::text[] WHERE slug = 'astaxanthin';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'astragalus';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'atenolol';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'atomoxetine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'atorvastatin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'azithromycin';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular']::text[] WHERE slug = 'banaba-leaf';
UPDATE public.compounds SET goal_tags = ARRAY['endurance', 'recovery', 'muscle']::text[] WHERE slug = 'bcaas';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'benfotiamine';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular']::text[] WHERE slug = 'berberine';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular']::text[] WHERE slug = 'berberine-hcl';
UPDATE public.compounds SET goal_tags = ARRAY['endurance', 'brain', 'muscle']::text[] WHERE slug = 'beta-alanine';
UPDATE public.compounds SET goal_tags = ARRAY['prostate', 'mens-longevity']::text[] WHERE slug = 'beta-sitosterol';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'endurance']::text[] WHERE slug = 'betaine-anhydrous';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'bitter-melon';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'immune', 'blood-sugar']::text[] WHERE slug = 'black-seed-oil';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'endurance']::text[] WHERE slug = 'boldenone-undecylenate';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'brain', 'testosterone', 'bone-joint', 'mens-longevity']::text[] WHERE slug = 'boron';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'recovery']::text[] WHERE slug = 'boron-glycinate';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'boswellia-serrata';
UPDATE public.compounds SET goal_tags = ARRAY['recovery']::text[] WHERE slug = 'bpc-157';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'brain']::text[] WHERE slug = 'bpc-157-arginate';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'bone-joint']::text[] WHERE slug = 'bromelain';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'bupropion';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'buspirone';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'caffeine';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'cardiovascular']::text[] WHERE slug = 'cagrilintide';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'menopause', 'womens-longevity']::text[] WHERE slug = 'calcium';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular', 'weight-loss']::text[] WHERE slug = 'cardarine';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'longevity']::text[] WHERE slug = 'cardiogen';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'carvedilol';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'casein-protein';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'celecoxib';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'cephalexin';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'cerebrolysin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'cetirizine';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'chaga-mushroom';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'cardiovascular', 'blood-sugar']::text[] WHERE slug = 'chlorella';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'choline-bitartrate';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'chondroitin-sulfate';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss']::text[] WHERE slug = 'chromium-picolinate';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular']::text[] WHERE slug = 'cinnamon-extract';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ciprofloxacin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'citalopram';
UPDATE public.compounds SET goal_tags = ARRAY['skin-hair', 'recovery']::text[] WHERE slug = 'cjc-1295';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'muscle']::text[] WHERE slug = 'cla';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'clomiphene-citrate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'clonidine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'clopidogrel';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'colchicine';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'muscle', 'skin-hair', 'menopause', 'womens-longevity']::text[] WHERE slug = 'collagen';
UPDATE public.compounds SET goal_tags = ARRAY['skin-hair', 'recovery']::text[] WHERE slug = 'copper-peptide-ghk';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'cardiovascular', 'fertility', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'coq10';
UPDATE public.compounds SET goal_tags = ARRAY['endurance']::text[] WHERE slug = 'cordyceps';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'brain', 'menopause', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'creatine';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'cardiovascular', 'bone-joint']::text[] WHERE slug = 'curcumin';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'immune']::text[] WHERE slug = 'cycloastragenol';
UPDATE public.compounds SET goal_tags = ARRAY['endurance']::text[] WHERE slug = 'd-ribose';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'dabigatran';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'delta-sleep-inducing-peptide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'dexmethylphenidate';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'dha-algae-oil';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'libido', 'fertility', 'menopause', 'womens-longevity']::text[] WHERE slug = 'dhea';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'diclofenac';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'cardiovascular']::text[] WHERE slug = 'dihydroberberine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'diphenhydramine';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'dl-phenylalanine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'doxycycline';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss']::text[] WHERE slug = 'dulaglutide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'duloxetine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'dutasteride';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'eaas';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'ecdysterone';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar']::text[] WHERE slug = 'ecnoglutide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'enalapril';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'bone-joint', 'muscle']::text[] WHERE slug = 'enclomiphene';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'enclomiphene-citrate';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'immune']::text[] WHERE slug = 'epitalon-aegg';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'sleep']::text[] WHERE slug = 'epithalon';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'brain', 'longevity']::text[] WHERE slug = 'ergothioneine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'escitalopram';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'esomeprazole';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'menopause', 'womens-longevity']::text[] WHERE slug = 'estradiol';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'testosterone', 'menopause', 'womens-longevity']::text[] WHERE slug = 'estradiol-valerate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'eszopiclone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'exemestane';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar']::text[] WHERE slug = 'exenatide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ezetimibe';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'libido']::text[] WHERE slug = 'fadogia-agrestis';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'famotidine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'fenofibrate';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'testosterone', 'cardiovascular', 'weight-loss']::text[] WHERE slug = 'fenugreek';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss', 'cardiovascular']::text[] WHERE slug = 'fgf-21-analog';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'finasteride';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'finasteride-1mg';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'longevity']::text[] WHERE slug = 'fisetin';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'fish-oil-high-epa';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'fluconazole';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'fluoxetine';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone']::text[] WHERE slug = 'fluoxymesterone';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'cardiovascular', 'fertility', 'womens-longevity']::text[] WHERE slug = 'folate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'furosemide';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'sleep']::text[] WHERE slug = 'gaba';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'gabapentin';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'skin-hair']::text[] WHERE slug = 'ghk-cu';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'ghrh-1-29';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'ghrp-2';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'recovery', 'muscle']::text[] WHERE slug = 'ghrp-6';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'glucosamine-sulfate';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'immune', 'muscle']::text[] WHERE slug = 'glutamine';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'mitochondria']::text[] WHERE slug = 'glutathione';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'sleep']::text[] WHERE slug = 'glycine';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'muscle']::text[] WHERE slug = 'gonadorelin';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'weight-loss', 'brain']::text[] WHERE slug = 'green-tea-extract';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'guanfacine';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'blood-sugar']::text[] WHERE slug = 'gymnema-sylvestre';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone']::text[] WHERE slug = 'hcg';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'cardiovascular', 'immune']::text[] WHERE slug = 'holy-basil';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'weight-loss']::text[] WHERE slug = 'hordenine';
UPDATE public.compounds SET goal_tags = ARRAY['libido']::text[] WHERE slug = 'horny-goat-weed';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'mitochondria', 'longevity', 'blood-sugar']::text[] WHERE slug = 'humanin';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'bone-joint', 'skin-hair', 'womens-longevity']::text[] WHERE slug = 'hyaluronic-acid-oral';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'hydrochlorothiazide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'hydrocortisone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ibuprofen';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'sleep']::text[] WHERE slug = 'ibutamoren-analog';
UPDATE public.compounds SET goal_tags = ARRAY['recovery']::text[] WHERE slug = 'igf-1-des-1-3';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'brain', 'fertility', 'womens-longevity']::text[] WHERE slug = 'inositol';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar']::text[] WHERE slug = 'insulin-long-acting';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar']::text[] WHERE slug = 'insulin-rapid';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'immune']::text[] WHERE slug = 'inulin-prebiotic';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'iodine';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss']::text[] WHERE slug = 'ipamorelin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'isotretinoin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ivermectin';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone']::text[] WHERE slug = 'kisspeptin-10';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'cardiovascular', 'brain']::text[] WHERE slug = 'klotho-peptide';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain', 'bone-joint']::text[] WHERE slug = 'krill-oil';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'recovery', 'endurance', 'immune']::text[] WHERE slug = 'l-arginine';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'weight-loss', 'endurance', 'cardiovascular']::text[] WHERE slug = 'l-carnitine';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'endurance']::text[] WHERE slug = 'l-citrulline';
UPDATE public.compounds SET goal_tags = ARRAY['sleep', 'brain']::text[] WHERE slug = 'l-theanine-sleep';
UPDATE public.compounds SET goal_tags = ARRAY['sleep']::text[] WHERE slug = 'l-tryptophan';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'lansoprazole';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'letrozole';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'recovery']::text[] WHERE slug = 'leucine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'levocetirizine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'levothyroxine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'levothyroxine-sodium';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint', 'testosterone']::text[] WHERE slug = 'ligandrol';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'lion-s-mane-mushroom';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'liothyronine';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'liposomal-glutathione';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'liraglutide';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'lisdexamfetamine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'lisinopril';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'lithium-carbonate';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'longevity']::text[] WHERE slug = 'livagen';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss']::text[] WHERE slug = 'lixisenatide';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'immune']::text[] WHERE slug = 'll-37';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'loratadine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'losartan';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'lovastatin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'low-dose-naltrexone';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'prostate', 'mens-longevity']::text[] WHERE slug = 'lycopene';
UPDATE public.compounds SET goal_tags = ARRAY['libido', 'endurance', 'brain', 'menopause', 'womens-longevity']::text[] WHERE slug = 'maca-root';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'macimorelin';
UPDATE public.compounds SET goal_tags = ARRAY['sleep', 'cardiovascular', 'menopause', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'magnesium-glycinate';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria']::text[] WHERE slug = 'magnesium-malate';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'magnesium-taurate';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'cardiovascular', 'blood-sugar']::text[] WHERE slug = 'mazdutide';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'mechano-growth-factor';
UPDATE public.compounds SET goal_tags = ARRAY['libido', 'weight-loss']::text[] WHERE slug = 'melanotan-ii';
UPDATE public.compounds SET goal_tags = ARRAY['sleep']::text[] WHERE slug = 'melatonin';
UPDATE public.compounds SET goal_tags = ARRAY['sleep']::text[] WHERE slug = 'melatonin-extended-release';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone']::text[] WHERE slug = 'mesterolone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'metformin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'metformin-er';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'metformin-immediate-release';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'mitochondria']::text[] WHERE slug = 'methylene-blue';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'methylphenidate';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'muscle']::text[] WHERE slug = 'methyltestosterone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'metoprolol';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'metronidazole';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'minocycline';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'minoxidil-oral';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'mirtazapine';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'mk-2866-sublingual';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint', 'sleep', 'weight-loss']::text[] WHERE slug = 'mk-677';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'modafinil';
UPDATE public.compounds SET goal_tags = ARRAY['endurance', 'blood-sugar']::text[] WHERE slug = 'mots-c';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'blood-sugar']::text[] WHERE slug = 'mots-c-analog';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'recovery', 'skin-hair']::text[] WHERE slug = 'msm-powder';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'skin-hair']::text[] WHERE slug = 'msm-sulfur';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'mucuna-pruriens';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'brain']::text[] WHERE slug = 'nad-iv';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'mitochondria']::text[] WHERE slug = 'nad-sublingual';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'naltrexone-full-dose';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'muscle']::text[] WHERE slug = 'nandrolone-decanoate';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'nandrolone-phenylpropionate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'naproxen';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'nattokinase';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ndt-armour-thyroid';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'cardiovascular', 'brain', 'endurance', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'nmn';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'nortriptyline';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'brain', 'womens-longevity']::text[] WHERE slug = 'nr';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'mitochondria', 'cardiovascular']::text[] WHERE slug = 'nr-resveratrol';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'fertility', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'omega-3';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'omeprazole';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'omeprazole-prilosec';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar']::text[] WHERE slug = 'orforglipron';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'ostarine';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar', 'weight-loss', 'brain', 'bone-joint']::text[] WHERE slug = 'osteocalcin';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'muscle', 'recovery']::text[] WHERE slug = 'oxandrolone';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'oxymetholone';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'oxytocin';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'immune', 'blood-sugar', 'endurance']::text[] WHERE slug = 'panax-ginseng';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'pantoprazole';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'paroxetine';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'sleep']::text[] WHERE slug = 'passionflower';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'pentosan-polysulfate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'phenelzine';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'phosphatidylserine';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'phosphorus';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'mens-longevity']::text[] WHERE slug = 'pine-bark-extract';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'bone-joint']::text[] WHERE slug = 'potassium';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'mitochondria']::text[] WHERE slug = 'pqq';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'recovery']::text[] WHERE slug = 'pralmorelin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'pravastatin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'prednisone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'pregabalin';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'pregnenolone';
UPDATE public.compounds SET goal_tags = ARRAY['endurance', 'cardiovascular']::text[] WHERE slug = 'propionyl-l-carnitine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'propranolol';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'weight-loss', 'immune']::text[] WHERE slug = 'protein';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar']::text[] WHERE slug = 'psyllium-husk';
UPDATE public.compounds SET goal_tags = ARRAY['libido']::text[] WHERE slug = 'pt-141';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'pterostilbene';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'immune', 'endurance', 'longevity']::text[] WHERE slug = 'quercetin';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'blood-sugar']::text[] WHERE slug = 'r-alpha-lipoic-acid';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'raloxifene';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ramelteon';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ramipril';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'ranitidine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'rapamycin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'rasagiline';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'menopause', 'womens-longevity']::text[] WHERE slug = 'red-clover';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'immune']::text[] WHERE slug = 'reishi-mushroom';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'brain', 'cardiovascular', 'womens-longevity']::text[] WHERE slug = 'resveratrol';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'retatrutide';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'retatrutide-ly';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'rhodiola-rosea';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'rivaroxaban';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'rosuvastatin';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 's-23';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'bone-joint']::text[] WHERE slug = 'sam-e';
UPDATE public.compounds SET goal_tags = ARRAY['prostate', 'mens-longevity']::text[] WHERE slug = 'saw-palmetto';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'selegiline';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'selenium';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'cardiovascular', 'blood-sugar']::text[] WHERE slug = 'semaglutide';
UPDATE public.compounds SET goal_tags = ARRAY['longevity']::text[] WHERE slug = 'sermorelin-acetate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'sertraline';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'sertraline-hcl';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'setria-glutathione';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'mens-longevity']::text[] WHERE slug = 'shilajit';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'sildenafil';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint']::text[] WHERE slug = 'silica';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'simvastatin';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain', 'menopause', 'womens-longevity']::text[] WHERE slug = 'soy-isoflavones';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'womens-longevity']::text[] WHERE slug = 'spermidine';
UPDATE public.compounds SET goal_tags = ARRAY['longevity', 'brain', 'cardiovascular']::text[] WHERE slug = 'spermidine-wheat';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'spironolactone';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'spironolactone-topical';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'spirulina';
UPDATE public.compounds SET goal_tags = ARRAY['endurance']::text[] WHERE slug = 'sr-9009';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint']::text[] WHERE slug = 'stanozolol';
UPDATE public.compounds SET goal_tags = ARRAY['prostate', 'mens-longevity']::text[] WHERE slug = 'stinging-nettle-root';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'suvorexant';
UPDATE public.compounds SET goal_tags = ARRAY['mens-longevity']::text[] WHERE slug = 'tadalafil';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'tamoxifen';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'sleep']::text[] WHERE slug = 'tart-cherry-extract';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'brain', 'cardiovascular']::text[] WHERE slug = 'tb-500-fragment';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'brain']::text[] WHERE slug = 'tesamorelin';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss']::text[] WHERE slug = 'tesamorelin-acetate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'tesofensine';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'bone-joint', 'testosterone', 'brain']::text[] WHERE slug = 'testolone';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'bone-joint', 'libido', 'mens-longevity']::text[] WHERE slug = 'testosterone-cypionate';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'muscle', 'libido', 'bone-joint']::text[] WHERE slug = 'testosterone-enanthate';
UPDATE public.compounds SET goal_tags = ARRAY['libido', 'testosterone', 'bone-joint', 'muscle']::text[] WHERE slug = 'testosterone-propionate';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'muscle', 'libido']::text[] WHERE slug = 'testosterone-sustanon';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'libido', 'bone-joint']::text[] WHERE slug = 'testosterone-trt';
UPDATE public.compounds SET goal_tags = ARRAY['testosterone', 'brain', 'libido', 'bone-joint']::text[] WHERE slug = 'testosterone-undecanoate';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'thymalin';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'thymosin-alpha-1';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'cardiovascular', 'skin-hair']::text[] WHERE slug = 'thymosin-beta-4';
UPDATE public.compounds SET goal_tags = ARRAY['weight-loss', 'blood-sugar', 'cardiovascular']::text[] WHERE slug = 'tirzepatide';
UPDATE public.compounds SET goal_tags = ARRAY['endurance']::text[] WHERE slug = 'tmg';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'tocotrienols';
UPDATE public.compounds SET goal_tags = ARRAY['libido', 'muscle', 'mens-longevity']::text[] WHERE slug = 'tongkat-ali';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'tranylcypromine';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'trazodone';
UPDATE public.compounds SET goal_tags = ARRAY['libido', 'cardiovascular']::text[] WHERE slug = 'tribulus-terrestris';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'testosterone']::text[] WHERE slug = 'turinabol';
UPDATE public.compounds SET goal_tags = ARRAY['muscle']::text[] WHERE slug = 'turkesterone';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'turkey-tail';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'recovery', 'bone-joint']::text[] WHERE slug = 'turmeric-curcumin-complex';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'mitochondria']::text[] WHERE slug = 'ubiquinol';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria', 'cardiovascular', 'longevity']::text[] WHERE slug = 'ubiquinone';
UPDATE public.compounds SET goal_tags = ARRAY['longevity']::text[] WHERE slug = 'urolithin-a';
UPDATE public.compounds SET goal_tags = ARRAY['sleep']::text[] WHERE slug = 'valerian-root';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'valsartan';
UPDATE public.compounds SET goal_tags = ARRAY['blood-sugar']::text[] WHERE slug = 'vanadium';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'vardenafil';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'venlafaxine';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'ventfort';
UPDATE public.compounds SET goal_tags = ARRAY['immune']::text[] WHERE slug = 'vitamin-a';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'vitamin-b-complex';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'mitochondria']::text[] WHERE slug = 'vitamin-b1-thiamine';
UPDATE public.compounds SET goal_tags = ARRAY['brain']::text[] WHERE slug = 'vitamin-b12';
UPDATE public.compounds SET goal_tags = ARRAY['mitochondria']::text[] WHERE slug = 'vitamin-b2-riboflavin';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular']::text[] WHERE slug = 'vitamin-b3-niacin';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'cardiovascular']::text[] WHERE slug = 'vitamin-b5-pantothenic-acid';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'immune']::text[] WHERE slug = 'vitamin-b6';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'cardiovascular', 'recovery']::text[] WHERE slug = 'vitamin-c';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'immune']::text[] WHERE slug = 'vitamin-d2-ergocalciferol';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'immune', 'brain', 'bone-joint', 'fertility', 'menopause', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'vitamin-d3';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'bone-joint', 'cardiovascular']::text[] WHERE slug = 'vitamin-d3-k2';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'cardiovascular']::text[] WHERE slug = 'vitamin-e';
UPDATE public.compounds SET goal_tags = ARRAY['bone-joint', 'menopause', 'mens-longevity', 'womens-longevity']::text[] WHERE slug = 'vitamin-k2';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'bone-joint']::text[] WHERE slug = 'vitamin-k2-mk-4';
UPDATE public.compounds SET goal_tags = ARRAY['cardiovascular', 'bone-joint']::text[] WHERE slug = 'vitamin-k2-mk-7';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'warfarin';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'warfarin-coumadin';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'weight-loss', 'recovery']::text[] WHERE slug = 'whey-protein-isolate';
UPDATE public.compounds SET goal_tags = ARRAY['brain', 'weight-loss']::text[] WHERE slug = 'yerba-mate';
UPDATE public.compounds SET goal_tags = ARRAY['muscle', 'testosterone']::text[] WHERE slug = 'yk-11';
UPDATE public.compounds SET goal_tags = ARRAY['recovery', 'immune']::text[] WHERE slug = 'zinc';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'recovery', 'brain']::text[] WHERE slug = 'zinc-bisglycinate';
UPDATE public.compounds SET goal_tags = ARRAY['immune', 'recovery', 'brain', 'mens-longevity']::text[] WHERE slug = 'zinc-picolinate';
UPDATE public.compounds SET goal_tags = ARRAY[]::text[] WHERE slug = 'zolpidem';
