/**
 * Sitemap coverage guard.
 *
 * Parses src/routes/sitemap[.]xml.ts's static entries and compares them
 * against the actual public route files under src/routes. Enforces:
 *
 *   - Every indexable static public route file has a sitemap entry.
 *   - No sitemap entry points at a private (_authenticated) route,
 *     an api route, or a non-indexable page (/auth, /onboarding,
 *     /reset-password).
 *   - No sitemap entry points at a route file that no longer exists.
 *
 * Dynamic content (compounds, goals, help articles) is emitted at
 * request time from the database/config and not covered here — those
 * sources are validated by scripts/validate-* live-URL sweeps.
 */

import { describe, it, expect } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

const ROUTES_DIR = join(process.cwd(), "src", "routes");
const SITEMAP_FILE = join(ROUTES_DIR, "sitemap[.]xml.ts");

// Non-indexable public routes: they legitimately opt out of search
// listings via robots: noindex and MUST NOT appear in the sitemap.
const NON_INDEXABLE = new Set<string>([
  "/auth",
  "/onboarding",
  "/reset-password",
  "/promo-kit",
  "/debug/index-check",
  "/debug/noindex-audit",
  // Internal diagnostics page: noindex, never listed for crawlers.
  "/debug/env",
  "/debug/deep-link",
  // Private OAuth redirect target: ssr:false, robots noindex/nofollow.
  "/auth_/callback",
]);

// Layout wrappers and utilities that don't render their own page.
const SKIP_FILES = new Set<string>([
  "__root.tsx",
  "library.tsx",
  "sitemap[.]xml.ts",
  // Non-HTML machine endpoints: they are not pages and are discovered
  // directly (robots.txt / <link rel="alternate">), not via the sitemap.
  "feed[.]xml.ts",
  "articles.feed[.]xml.ts",
  "llms-full[.]txt.ts",
  // Agent/OAuth machine endpoints: JSON transports and a consent screen for
  // connected agents, not crawlable pages.
  "mcp.ts",
  "[.]lovable.oauth.consent.tsx",
]);

function filenameToPath(file: string): string {
  const base = file.replace(/\.tsx?$/, "");
  if (base === "index") return "/";
  let p = "/" + base.replace(/\./g, "/");
  p = p.replace(/\/index$/, "");
  return p || "/";
}

function isCandidatePublicRoute(file: string): boolean {
  if (SKIP_FILES.has(file)) return false;
  if (!/\.tsx?$/.test(file)) return false;
  if (file.startsWith("_")) return false; // _authenticated
  if (file.startsWith("api.")) return false;
  if (file.startsWith("lovable")) return false;
  if (file.includes("$")) return false; // dynamic — handled by DB
  return true;
}

// Redirect-only alias routes (beforeLoad throws redirect(), no component)
// are not pages: they must NOT appear in the sitemap.
function isRedirectAlias(file: string): boolean {
  const src = readFileSync(join(ROUTES_DIR, file), "utf8");
  return /throw redirect\(/.test(src) && !/component:/.test(src);
}

function collectPublicRoutePaths(): Set<string> {
  const files = readdirSync(ROUTES_DIR)
    .filter(isCandidatePublicRoute)
    .filter((f) => !isRedirectAlias(f));
  return new Set(files.map(filenameToPath));
}

function collectSitemapStaticPaths(): string[] {
  const src = readFileSync(SITEMAP_FILE, "utf8");
  const paths = Array.from(src.matchAll(/\{\s*path:\s*"([^"]+)"/g)).map((m) => m[1]);
  // /blog and its paginated pages are generated by blogListSitemapPaths().
  if (src.includes("blogListSitemapPaths(")) paths.push("/blog");
  return paths;
}

function collectAuthenticatedPaths(): Set<string> {
  const dir = join(ROUTES_DIR, "_authenticated");
  const out = new Set<string>();
  try {
    for (const f of readdirSync(dir)) {
      if (!/\.tsx?$/.test(f)) continue;
      out.add(filenameToPath(f));
    }
  } catch {
    // no _authenticated dir — fine
  }
  return out;
}

describe("sitemap.xml", () => {
  const publicPaths = collectPublicRoutePaths();
  const sitemapPaths = collectSitemapStaticPaths();
  const sitemapSet = new Set(sitemapPaths);
  const authPaths = collectAuthenticatedPaths();

  it("lists every indexable static public route", () => {
    const missing = [...publicPaths]
      .filter((p) => !NON_INDEXABLE.has(p))
      .filter((p) => !sitemapSet.has(p))
      .sort();
    expect(missing, `Missing sitemap entries: ${missing.join(", ")}`).toEqual([]);
  });

  it("excludes non-indexable public pages (/auth, /onboarding, /reset-password)", () => {
    const leaked = [...NON_INDEXABLE].filter((p) => sitemapSet.has(p));
    expect(leaked, `Non-indexable in sitemap: ${leaked.join(", ")}`).toEqual([]);
  });

  it("excludes every authenticated (_authenticated/*) route", () => {
    const leaked = [...authPaths].filter((p) => sitemapSet.has(p));
    expect(leaked, `Authenticated routes in sitemap: ${leaked.join(", ")}`).toEqual([]);
  });

  it("excludes every /api/* server route", () => {
    const leaked = sitemapPaths.filter((p) => p.startsWith("/api/"));
    expect(leaked, `API routes in sitemap: ${leaked.join(", ")}`).toEqual([]);
  });

  it("has no duplicate entries", () => {
    const dupes = sitemapPaths.filter((p, i) => sitemapPaths.indexOf(p) !== i);
    expect(dupes, `Duplicate sitemap entries: ${dupes.join(", ")}`).toEqual([]);
  });

  it("every entry resolves to a real route file or is a hub/quick-action path", () => {
    // Anything that looks like a static top-level page must have a
    // matching file. Dynamic children (e.g. /library/<compound-slug>)
    // are allowed via the compound loader — those are the entries that
    // don't map 1:1 to a file and aren't in the static list anyway.
    const orphans = sitemapPaths.filter((p) => {
      if (publicPaths.has(p)) return false;
      // Deep dynamic paths served by loaders are appended at runtime,
      // so anything hardcoded should map to a file. If it doesn't, flag.
      return true;
    });
    expect(orphans, `Sitemap entries with no matching route file: ${orphans.join(", ")}`).toEqual(
      [],
    );
  });
});
